config/routes.rb
Tutoria::Application.routes.draw do

  resources :users
    match "/start", :to => "users#start"

  resources :sessions, :only => [:create, :destroy]
    match "/signout", :to => "sessions#destroy", :via => :delete 

  root :to => 'Home#index'
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
  
  belongs_to :user
  
  validates :content, :length => { :maximum => 100 }
end
# == Schema Information
#
# Table name: microposts
#
#  id         :integer         not null, primary key
#  content    :text
#  user_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_secure_password #this is a ActiveModel helper for storing "password_digest"
  
  #constants and definitions
  EMAIL_REGEX = /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[A-Z]{2,4}$/i
  
  #validations
  validates :name,  :presence => true,
                    :uniqueness => true,
                    :length => { :in => 3..20 }
  validates :email, :presence => true,
                    :uniqueness => { :case_sensitive => false },
                    :format => EMAIL_REGEX
  validates :password,  :presence => true,
                        :length => {in: 4..20}
  validates :password_confirmation, :presence => true

  #callback functions
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  #private functions
  private
    def create_remember_token
      # I think it's equal to User.remember_token?
      self.remember_token = SecureRandom.urlsafe_base64 
    end
end
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  include SessionsHelper #this is a helper for checking sessions-tokens in different pages

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(params[:micropost])

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render json: @micropost, status: :created, location: @micropost }
      else
        format.html { render action: "new" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user_path(user)
		else
			flash[:error] = "email/password not match"
			redirect_to start_path
		end
	end
	
	def destroy
		sign_out
		redirect_to root_path
	end

end

#Why that I can only use "user" instead of "@user"?????

app/controllers/starts_controller.rb
class StartsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def start
    @user = User.new
  end

  def create
    @user = User.new(params[:user]) #this "params" is from html forms
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Tutoria!"
      redirect_to user_path(@user)
    else
      render "start"
    end
  end

  def show
    @user = User.find(params[:id]) #this "params" is for querying
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def sign_in(user)
		cookies[:remember_token] = { :value => user.remember_token,
																 :expires =>	21.days.from_now.utc}
		#This assigned the attribute "current_user", not a local variable 
		self.current_user = user 
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
end

#what's going on with this helper????

app/helpers/starts_helper.rb
module StartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  #returns the gravatar according to the user's email
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    return  image_tag(gravatar_url, alt: user.name, class:"gravatar")
  end
end

app/views/home/index.html.erb
<div class="hero-unit center">
  <h1>Tutoria!</h1>
  <h2>This is the easiest tutorial writting/reading web app.<br/>
    <%= link_to "Try the demo", root_path, :class => "btn btn-large btn-primary" %>
    or just
    
    <% if signed_in? %>
    	<%= link_to "Start!", user_path(current_user), :class => "btn btn-large btn-primary" %> 
    	<% else %>    
    	<%= link_to "Start!", start_path, :class => "btn btn-large btn-primary" %> 
    <% end %>
  
  </h2>
</div>
<!-- END .hero-unit .center -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
      <div>&copy Tutoria! 2012. Built by uplaabura. </div> 
  </div>
</footer>

app/views/layouts/_forIE.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner"> 
    <div class="container-fluid">

      <%= link_to "Tutoria!", root_path, :class => "brand" %>
      
      <!-- collapse navbar for responsive design -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <!-- user button -->
      <% if signed_in? %>
        <div class="btn-group pull-right">                           
          <button class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> <%= current_user.name %>
              <span class="caret"></span>
          </button>

          <ul class="dropdown-menu">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Settings", "#" %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", signout_path, :method => "delete" %></li>
          </ul>
        </div>
        <!-- END .btn-group .pull-right-->
      <% else %>
        <%= link_to "Start!", start_path, :class => "btn pull-right" %>
      <% end %>
 
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Home", "#" %></li>
          <li><%= link_to "Tutoria!", "#" %></li>
        </ul>
      </div>
      <!-- END .nav-collapse -->
    </div>
    <!-- END .container-fluid -->
  </div>
  <!-- END .navbar-inner -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Tutoria!</title>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render "layouts/forIE" %>

    <!-- Google JQuery API -->
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script>google.load("jquery", "1.6.2");</script>

  </head>

  <body>
  
    <%= render "layouts/header" %>

    <div class="wrapper">
      <div class="container">
        
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>

        <%= yield %>
    
        <%= debug(params) if Rails.env.development? %>
    
      </div>
      <!-- END .container -->
      <div class="push"><!-- For sticky footer --></div>
    </div>
    <!-- END .wrapper -->
    
    <%= render "layouts/footer" %>
    
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @micropost.user_id %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_messages">
		<div class="alert alert-error">
			<a href="#" class="close" data-dismiss="alert">x</a>
			<em>Warning! </em><%= pluralize(@user.errors.count, "error") %>
		</div>
		<!-- END .alert .alert-error -->
		<ul>
			<% @user.errors.full_messages.each do |full_messages| %>
			<li>* <%= full_messages %></li>
			<% end %>
		</ul>
	</div>
	<!-- END #error-messages -->
<% end %>

app/views/users/_signin.html.erb
<h1>Sign in</h1>

  <%= form_for(:session, :url => sessions_path) do |signin_form| %>
    <%= signin_form.label :email %>
    <%= signin_form.text_field :email %>

    <%= signin_form.label :password %>
    <%= signin_form.password_field :password %>

    <%= signin_form.submit "Sign in!", class:"btn btn-large btn-primary" %>
  <% end %>

app/views/users/_signup.html.erb
<h1>Sign up</h1>

  <%= form_for(@user) do |signup_form| %>
    <%= signup_form.label :name %>
    <%= signup_form.text_field :name %>
  
    <%= signup_form.label :email %>
    <%= signup_form.text_field :email %>
  
    <%= signup_form.label :password %>
    <%= signup_form.password_field :password %>

    <%= signup_form.label :password_confirmation %>
    <%= signup_form.password_field :password_confirmation %>

    <%= signup_form.submit "Start!", class:"btn btn-large btn-primary" %>
  <% end %>

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
    <h1>
    <%= gravatar_for @user %>
    <%= @user.name %> 
    </h1>
  </section>
  </aside>
</div>

app/views/users/start.html.erb
<div class="row">
  <div class="span12">
    <div class="row">

      <!-- Signup Form 
      ==================================== -->
      <div class="span6">
        <div class="row">
          <div class="span4 offset1">

            <%= render "shared/error_messages" %>
          
            <%= render "users/signup" %>

          </div>
          <!-- END .span4 .offset1 -->  
        </div>
        <!-- END .row -->
      </div>
      <!-- END .span6 .leftside -->
      
      <!-- Signin Form
      ==================================== -->
      <div class="span6">
        <div class="row">
          <div class="span4 offset1">
           
            <%= render "users/signin" %>

          </div>
          <!-- END .span4 .offset1 -->
        </div>
        <!-- END .row -->
      </div>  
      <!-- END .span6 -->
    

    </div>
    <!-- END .row -->
  </div>
  <!-- END .span12 -->
</div>
<!-- END .row -->   